name:                yaftee-conduit
version:             0.1.0.1
github:              "YoshikuniJujo/yaftee-conduit"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Conduit implemented on Yaftee
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/yaftee-conduit#readme>

dependencies:
- base >= 4.7 && < 5
- yaftee >= 0.1 && < 0.2
- yaftee-basic-monads >=0.1 && < 0.2
- higher-order-freer-monad >=0.1 && < 0.2
- higher-order-open-union >= 0.1 && < 0.2
- ftcqueue >= 0.1 && < 0.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  yaftee-conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaftee-conduit
